kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: ephemeral-test
  namespace: testkube
  labels:
    test: k6
spec:
  content:
    git:
      uri: https://github.com/cerebro1/testkube-ephemeral
      revision: main
      paths:
        - k6/testkube.js
  container:
    workingDir: /data/repo/k6/
  steps:
    - name: Run test
      container:
        image: grafana/k6:0.49.0
      shell: |
        k6 run testkube.js
      artifacts:
        workingDir: /data
        paths:
          - '*.html'
