name: Ephemeral Test Using Testkube
on:
  pull_request: 

jobs:
  testkube-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Kind Cluster
        uses: helm/kind-action@v1.12.0

      - name: Setup Testkube with Helm
        run: |
          helm repo add kubeshop https://kubeshop.github.io/helm-charts; 

      - name: Configure Testkube Agent
        run: |
          helm repo update
          helm upgrade --install --create-namespace --namespace testkube testkube kubeshop/testkube

      - name: Check Testkube Version and Pods Status
        run: |
          kubectl get pods -n testkube -o wide
          POD_NAME=$(kubectl get pods -n testkube | grep testkube-api-server | awk '{print $1}')
          kubectl wait --for=condition=Ready pod/$POD_NAME -n testkube --timeout=150s

      - name: Setup Testkube
        uses: kubeshop/setup-testkube@v1.0.8

      - name: Create and run Test Workflow
        run: |
          testkube create testworkflow -f testworkflow.yaml   
          testkube run tw ephemeral-test --watch
